[project]
name = "maddr-api"
version = "0.1.0"
description = ""
authors = [
    {name = "lucas.harmatiuk",email = "lucasjharmatiuk@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "maddr_api", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
