"""add book table

Revision ID: 0a3b81d2908e
Revises: 521a8c97c8d0
Create Date: 2025-10-30 08:50:16.512072

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0a3b81d2908e"
down_revision: Union[str, Sequence[str], None] = "521a8c97c8d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
