"""atualizando

Revision ID: 1bc8a193d396
Revises: dc1cc5612a1d
Create Date: 2025-11-05 09:01:33.972199

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1bc8a193d396"
down_revision: Union[str, Sequence[str], None] = "dc1cc5612a1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
