"""Adiciona relacionamento entre Book e Author

Revision ID: 9f68c1803af6
Revises: cec21cc157f7
Create Date: 2025-11-05 09:25:23.174188

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9f68c1803af6"
down_revision: Union[str, Sequence[str], None] = "cec21cc157f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_book_author_id", "author", ["author_id"], ["id"]
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "book", type_="foreignkey")
    # ### end Alembic commands ###
