"""add author table

Revision ID: ae6e9ad009b0
Revises: 1bc8a193d396
Create Date: 2025-11-05 09:04:03.317441

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ae6e9ad009b0"
down_revision: Union[str, Sequence[str], None] = "1bc8a193d396"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
